project:
  type: website
  output-dir: docs

website:
  title: "Spatial R - Using R as a GIS"
  sidebar:
    style: "floating"
    search: false
    contents:
      - index.qmd
      - section: "Basics"
        contents:
          - geodata.qmd
          - geodata_r.qmd
          - vector_data.qmd
          - vector_ex01.qmd
          - raster_data.qmd
          - raster_ex01.qmd
      - section: "Advanced"
        contents: 
          - projections.qmd
          - gis_software.qmd
          - rsaga.qmd
      - section: "Additional Resources"
        contents:
          - literature.qmd
          - references.qmd

    

bibliography: "../../literature/zotero/references.bib"
number-depth: 0

format:
  html:
    theme: materia
    number-sections: false
    grid:
      sidebar-width: 350px
execute: 
  warning: false
  message: false

