---
title: "R als GIS"
description: |
  This is a slide and exercise collection for the ILOEK Course "R als GIS".
link-citations: true
github-repo: LOEK-RS-Class/r_gis
crossrefs-hover: true
crossref: 
  fig-labels: arabic
---



```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, include = TRUE)
```


```{r}
#| echo: false
knitr::include_url("i00_intro_slides.html")
```


## Course Outline

+-------+-------------+----------------+-----------------------------+-------------+-----------+
|       | Monday      | Tuesday        | Wednesday                   | Thursday    | Friday    |
+=======+=============+================+=============================+=============+===========+
|09:00\ | Geodata I/O | Raster data    | Digital Terrain Models\     | Programming | Projects  |
|12:00  |             |                | Using GIS software in R     |             |           |
+-------+-------------+----------------+-----------------------------+-------------+-----------+
|       |             |                |                             |             |           |
+-------+-------------+----------------+-----------------------------+-------------+-----------+
|13:00\ | Vector data | Projections\   | R Markdown                  | Projects    | Projects  |
|16:00  |             | Visualizations |                             |             |           |
+-------+-------------+----------------+-----------------------------+-------------+-----------+

